version: '3'

services:
    app:
        build: .
        entrypoint: .docker/entrypoint.sh
        container_name: order-api
        ports:
            - "3333:3333"
        volumes:
            - .:/home/node/app
        depends_on:
            - db
            - redis
    db:
        build: .docker/postgres
        container_name: order-api-db
        restart: always
        tty: true
        ports:
            - "5432:5432"
        volumes:
            - .docker/dbdata:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=docker
            - POSTGRES_DB=order-api

    redis:
        image: 'bitnami/redis:latest'
        container_name: order-api-redis
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
